# Generated by Django 3.1.2 on 2020-11-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONOHC_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('Zip', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
