# Generated by Django 3.1.2 on 2020-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONOHC_app', '0004_auto_20201126_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='Zip',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='signin',
            name='city',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='signin',
            name='email',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='signin',
            name='password',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='signin',
            name='state',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='signin',
            name='username',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
